// ---------------------------------------------------------------------------
// AI Insights Service
// Uses Claude-generated narrative data baked into data.json at pipeline time.
// Falls back to rule-derived summary if narrative is absent.
// ---------------------------------------------------------------------------

import type { CountryData } from '../types/country'

export interface AIInsights {
  headline: string
  analysis: string
  watchPoints: string[]
  confidence: 'high' | 'medium' | 'low'
}

/**
 * Returns AI-generated insights for a country.
 * Primary source: narrative object in data.json (generated by Claude at build time).
 * Fallback: rule-derived summary from indicator trends.
 */
export async function getCountryInsights(country: CountryData): Promise<AIInsights> {
  // Use pre-generated Claude narrative from pipeline if available
  if (country.narrative?.headline && country.narrative?.summary) {
    const watchPoints: string[] =
      country.narrative.bullets?.length > 0
        ? country.narrative.bullets
        : _deriveWatchPoints(country)

    const confidence: AIInsights['confidence'] =
      country.flags.length >= 3 ? 'high' : country.flags.length >= 1 ? 'medium' : 'low'

    return {
      headline: country.narrative.headline,
      analysis: country.narrative.summary,
      watchPoints,
      confidence,
    }
  }

  // Fallback: derive from indicator data
  return _derivedInsights(country)
}

function _deriveWatchPoints(country: CountryData): string[] {
  const indicators = Object.values(country.indicators)
  const declining = indicators.filter(
    (ind) => ind.trend === 'declining' || ind.trend === 'rapidly_declining',
  )
  const points = declining.slice(0, 3).map((ind) => {
    const trendLabel = ind.trend === 'rapidly_declining' ? 'rapid decline' : 'declining trend'
    return `${ind.label} shows a ${trendLabel} (current value: ${ind.value.toFixed(1)})`
  })
  if (points.length === 0) {
    points.push(`${country.name} shows no rapidly deteriorating indicators at this time.`)
  }
  return points
}

function _derivedInsights(country: CountryData): AIInsights {
  const score = country.current_score
  const tier = country.current_tier_label
  const change5yr = country.five_year_change
  const changeDir = change5yr < 0 ? 'declined' : 'improved'
  const changeAbs = Math.abs(change5yr).toFixed(1)

  const confidence: AIInsights['confidence'] =
    country.flags.length >= 3 ? 'high' : country.flags.length >= 1 ? 'medium' : 'low'

  return {
    headline: `${country.name}: ${tier} democratic stress (score ${score.toFixed(1)})`,
    analysis:
      `${country.name} registers a composite democratic stress score of ${score.toFixed(1)}, ` +
      `placing it in the ${tier} tier. Over the past five years, stress has ${changeDir} by ${changeAbs} points. ` +
      `${country.flags.length > 0 ? `${country.flags.length} active risk flag(s) require monitoring.` : 'No active risk flags are present.'}`,
    watchPoints: _deriveWatchPoints(country),
    confidence,
  }
}
