import { CountryData } from "./services/geminiService";

export const MOCK_COUNTRIES: CountryData[] = [
  {
    name: "Brazil",
    isoCode: "BRA",
    currentScore: 58,
    status: "Elevated",
    indicators: {
      mediaFreedom: 55,
      judicialIndependence: 62,
      civilSociety: 58,
      electionQuality: 75,
      executiveConstraints: 52,
      rhetoricRadar: 45,
      civicProtests: 60,
    },
    history: [
      { year: 2010, score: 78 },
      { year: 2012, score: 82 },
      { year: 2014, score: 75 },
      { year: 2016, score: 68 },
      { year: 2018, score: 72 },
      { year: 2020, score: 65 },
      { year: 2022, score: 60 },
      { year: 2024, score: 58 },
    ],
    events: [
      { date: "Oct 2023", title: "Supreme Court powers curtailed", description: "Legislative amendment passed limiting individual justice injunctions.", type: "legal" },
      { date: "June 2023", title: "Mass anti-corruption protests", description: "Public demonstrations in 14 cities highlighting institutional trust erosion.", type: "protest" },
      { date: "Jan 2023", title: "New Transparency Law", description: "Executive order mandating real-time budget disclosure for municipalities.", type: "legal" },
    ],
  },
  {
    name: "Norway",
    isoCode: "NOR",
    currentScore: 94,
    status: "Stable",
    indicators: {
      mediaFreedom: 98,
      judicialIndependence: 95,
      civilSociety: 96,
      electionQuality: 97,
      executiveConstraints: 94,
      rhetoricRadar: 92,
      civicProtests: 90,
    },
    history: [
      { year: 2010, score: 95 },
      { year: 2015, score: 94 },
      { year: 2020, score: 95 },
      { year: 2024, score: 94 },
    ],
    events: [
      { date: "Dec 2023", title: "Freedom of Press Award", description: "National media association recognized for investigative excellence.", type: "political" },
    ],
  },
  {
    name: "Hungary",
    isoCode: "HUN",
    currentScore: 34,
    status: "Critical",
    indicators: {
      mediaFreedom: 18,
      judicialIndependence: 12,
      civilSociety: 42,
      electionQuality: 56,
      executiveConstraints: 25,
      rhetoricRadar: 15,
      civicProtests: 39,
    },
    history: [
      { year: 2010, score: 72 },
      { year: 2012, score: 65 },
      { year: 2014, score: 55 },
      { year: 2016, score: 48 },
      { year: 2018, score: 42 },
      { year: 2020, score: 38 },
      { year: 2022, score: 35 },
      { year: 2024, score: 34 },
    ],
    events: [
      { date: "Nov 2023", title: "Sovereignty Protection Act", description: "New law targeting foreign funding for NGOs and media outlets.", type: "legal" },
      { date: "Sept 2023", title: "Judicial Council Restructuring", description: "Government-appointed members now hold majority in key oversight body.", type: "legal" },
    ],
  },
  {
    name: "India",
    isoCode: "IND",
    currentScore: 52,
    status: "Elevated",
    indicators: {
      mediaFreedom: 41,
      judicialIndependence: 58,
      civilSociety: 45,
      electionQuality: 68,
      executiveConstraints: 54,
      rhetoricRadar: 38,
      civicProtests: 55,
    },
    history: [
      { year: 2010, score: 75 },
      { year: 2015, score: 68 },
      { year: 2020, score: 58 },
      { year: 2024, score: 52 },
    ],
    events: [
      { date: "Aug 2023", title: "Digital Personal Data Protection Act", description: "Concerns raised over government exemptions for data access.", type: "legal" },
    ],
  },
];
